name: Black formatting

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Run Black
        run: black --check .
